# Replace lines marked '#' with your preferences.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: #
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #
  template:
    metadata:
      labels:
        app: #
    spec:
      containers:
      - name: #
        image: #
        ports:
        - containerPort: #
        - containerPort: #
