apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-dev-hot
  template:
    metadata:
      labels:
        app: pod-dev-hot
    spec:
      containers:
      - name: pod-dev-hot
        image: podpulse/pod-dev:latest
        ports:
        - containerPort: 8080
        - containerPort: 3333
