services:
  test:
    depends_on: [generic-test]
    image: podmdImage
    container_name: podmd-test
    ports: [3000:3000]
    volumes: [./:/user/src/app, node_modules:/user/src/app/node_modules]
    command: npm run test
  generic-test:
    image: podmdImage
    container_name: podmd-test
volumes:
  node_modules:
  test-db-volume: