apiVersion: v1
kind: Service
metadata:
  name: pod-dev-service
spec:
  type: NodePort
  ports:
    - name: front
      port: 8080
      targetPort: 8080
      nodePort: 30001
    - name: back
      port: 3333
      targetPort: 3333
      nodePort: 30002
  selector:
    app: pod-dev-hot
